# Generated by scripts/update_client.py from the OpenAPI snapshot; do not edit.
from typing import Literal, TypeAlias

from .pydantic_gen import (
    ImageArenaFreeResponse,
    ImageArenaResponse,
    LLMModelsFreeResponse,
    LLMModelsResponse,
    MusicArenaFreeResponse,
    MusicArenaResponse,
    SpeechToSpeechFreeResponse,
    SpeechToSpeechResponse,
    SpeechToTextModelsFreeResponse,
    SpeechToTextModelsResponse,
    TextToSpeechFreeResponse,
    TextToSpeechResponse,
    VideoArenaFreeResponse,
    VideoArenaResponse,
)

PromptType: TypeAlias = Literal["medium", "long", "100k", "vision_single_image", "medium_coding", "medium_parallel"]
Page: TypeAlias = (
    ImageArenaFreeResponse
    | ImageArenaResponse
    | LLMModelsFreeResponse
    | LLMModelsResponse
    | MusicArenaFreeResponse
    | MusicArenaResponse
    | SpeechToSpeechFreeResponse
    | SpeechToSpeechResponse
    | SpeechToTextModelsFreeResponse
    | SpeechToTextModelsResponse
    | TextToSpeechFreeResponse
    | TextToSpeechResponse
    | VideoArenaFreeResponse
    | VideoArenaResponse
)
RESPONSES: dict[str, type[Page]] = {
    "/api/v2/language/models": LLMModelsResponse,
    "/api/v2/language/models/free": LLMModelsFreeResponse,
    "/api/v2/media/image-editing/models": ImageArenaResponse,
    "/api/v2/media/image-editing/models/free": ImageArenaFreeResponse,
    "/api/v2/media/image-to-video-audio/models": VideoArenaResponse,
    "/api/v2/media/image-to-video-audio/models/free": VideoArenaFreeResponse,
    "/api/v2/media/image-to-video/models": VideoArenaResponse,
    "/api/v2/media/image-to-video/models/free": VideoArenaFreeResponse,
    "/api/v2/media/music/instrumental/models": MusicArenaResponse,
    "/api/v2/media/music/instrumental/models/free": MusicArenaFreeResponse,
    "/api/v2/media/music/with-vocals/models": MusicArenaResponse,
    "/api/v2/media/music/with-vocals/models/free": MusicArenaFreeResponse,
    "/api/v2/media/speech-to-speech/models": SpeechToSpeechResponse,
    "/api/v2/media/speech-to-speech/models/free": SpeechToSpeechFreeResponse,
    "/api/v2/media/speech-to-text/models": SpeechToTextModelsResponse,
    "/api/v2/media/speech-to-text/models/free": SpeechToTextModelsFreeResponse,
    "/api/v2/media/text-to-image/models": ImageArenaResponse,
    "/api/v2/media/text-to-image/models/free": ImageArenaFreeResponse,
    "/api/v2/media/text-to-speech/models": TextToSpeechResponse,
    "/api/v2/media/text-to-speech/models/free": TextToSpeechFreeResponse,
    "/api/v2/media/text-to-video-audio/models": VideoArenaResponse,
    "/api/v2/media/text-to-video-audio/models/free": VideoArenaFreeResponse,
    "/api/v2/media/text-to-video/models": VideoArenaResponse,
    "/api/v2/media/text-to-video/models/free": VideoArenaFreeResponse,
}
