# generated by datamodel-codegen:
#   filename:  selected-openapi.json

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field
from pydantic.experimental.missing_sentinel import MISSING


class ArenaCategory(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    label: Annotated[str, Field(description="Category label.")]
    elo: float
    ci_95: float | None
    samples: int


class ArenaModelCreator(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    error: str
    details: Annotated[
        dict[str, Any] | MISSING,
        Field(description="Additional error details (e.g. validation errors). Only present on some error responses."),
    ] = MISSING


class EvalTokenCounts(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    input_tokens: float
    answer_tokens: float
    output_tokens: float
    reasoning_tokens: float


class EvaluationTokenCounts(BaseModel):
    """
    Per-evaluation token counts for published benchmarks.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    hle: EvalTokenCounts | MISSING = MISSING
    aa_lcr: EvalTokenCounts | MISSING = MISSING
    gpqa_diamond: EvalTokenCounts | MISSING = MISSING
    tau2_telecom: EvalTokenCounts | MISSING = MISSING
    tau_banking: EvalTokenCounts | MISSING = MISSING
    critpt: EvalTokenCounts | MISSING = MISSING
    gdpval_aa: EvalTokenCounts | MISSING = MISSING
    ifbench: EvalTokenCounts | MISSING = MISSING
    scicode: EvalTokenCounts | MISSING = MISSING
    mmmu_pro: EvalTokenCounts | MISSING = MISSING
    aa_omniscience: EvalTokenCounts | MISSING = MISSING
    terminalbench_hard: EvalTokenCounts | MISSING = MISSING
    terminalbench_v2_1: EvalTokenCounts | MISSING = MISSING
    terminalbench_v4_0: EvalTokenCounts | MISSING = MISSING
    terminalbench_science: EvalTokenCounts | MISSING = MISSING


class Evaluations(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    artificial_analysis_intelligence_index: Annotated[
        float | None, Field(description="AA Intelligence Index composite score.")
    ]
    artificial_analysis_coding_index: Annotated[float | None, Field(description="AA Coding Index composite score.")]
    artificial_analysis_agentic_index: Annotated[float | None, Field(description="AA Agentic Index composite score.")]
    tau2_telecom: Annotated[
        float | None | MISSING,
        Field(description="τ²-Bench Telecom score. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    tau_banking: Annotated[
        float | None | MISSING,
        Field(description="τ³-Banking score. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    terminalbench_hard: Annotated[
        float | None | MISSING,
        Field(description="Terminal-Bench Hard score. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    terminalbench_v2_1: Annotated[
        float | None | MISSING,
        Field(description="Terminal-Bench 2.1 score. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    terminalbench_v4_0: Annotated[
        float | None | MISSING,
        Field(description="Terminal-Bench 4.0 score. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    terminalbench_science: Annotated[
        float | None | MISSING,
        Field(description="Terminal-Bench-Science 0.1 score. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    scicode: Annotated[
        float | None | MISSING,
        Field(description="SciCode score. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    aa_lcr: Annotated[
        float | None | MISSING,
        Field(description="AA-LCR score. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    aa_omniscience_index: Annotated[
        float | None | MISSING,
        Field(description="AA-Omniscience Index score. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    aa_omniscience_accuracy: Annotated[
        float | None | MISSING,
        Field(description="Aggregate Omniscience accuracy. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    aa_omniscience_non_hallucination_rate: Annotated[
        float | None | MISSING,
        Field(
            description="Aggregate Omniscience non-hallucination score (1 - hallucination_rate). Pro tier only. Omitted on Free tier."
        ),
    ] = MISSING
    ifbench: Annotated[
        float | None | MISSING,
        Field(description="IFBench score. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    hle: Annotated[
        float | None | MISSING,
        Field(description="Humanity's Last Exam score. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    gpqa_diamond: Annotated[
        float | None | MISSING,
        Field(description="GPQA Diamond score. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    critpt: Annotated[
        float | None | MISSING,
        Field(description="CritPt score. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    gdpval_aa_elo: Annotated[
        float | None | MISSING,
        Field(description="GDPval raw Elo score. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    gdpval_aa_normalized: Annotated[
        float | None | MISSING,
        Field(
            description="GDPval score normalized to a 0-1 scale, used in the Intelligence Index. Pro tier only. Omitted on Free tier."
        ),
    ] = MISSING
    mmmu_pro: Annotated[
        float | None | MISSING,
        Field(description="MMMU-Pro visual reasoning score. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    artificial_analysis_openness_index: Annotated[
        float | None | MISSING,
        Field(description="Openness Index score. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    artificial_analysis_multilingual_index: Annotated[
        float | None | MISSING,
        Field(description="Multilingual Index score. Pro tier only. Omitted on Free tier."),
    ] = MISSING
    mlcr_overall: Annotated[
        float | None | MISSING,
        Field(
            description="MLCR-AA (Medical Long Context Reasoning) overall pass rate. Pro tier only. Omitted on Free tier."
        ),
    ] = MISSING


class FreeEvaluations(BaseModel):
    """
    Composite Artificial Analysis indices. Pro tier adds per-benchmark scores.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    artificial_analysis_intelligence_index: Annotated[
        float | None, Field(description="AA Intelligence Index composite score.")
    ]
    artificial_analysis_coding_index: Annotated[float | None, Field(description="AA Coding Index composite score.")]
    artificial_analysis_agentic_index: Annotated[float | None, Field(description="AA Agentic Index composite score.")]


class FreeIntelligenceIndexCostPerTask(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    total_cost: Annotated[
        float,
        Field(
            description="Weighted average cost in USD per Intelligence Index task, across all Intelligence Index evaluations. Rounded to 4 decimal places."
        ),
    ]


class FreeModelCreator(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str


class FreeModelPerformance(BaseModel):
    """
    Median performance metrics across all providers serving this model. Individual fields are null when no measurements are available for that metric.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    median_output_tokens_per_second: float | None
    median_time_to_first_token_seconds: float | None
    median_time_to_first_answer_token_seconds: float | None
    median_end_to_end_response_time_seconds: float | None


class FreePricing(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    price_1m_input_tokens: Annotated[
        float | None,
        Field(description="Price per 1M input tokens. Null when pricing data is not available."),
    ]
    price_1m_output_tokens: Annotated[
        float | None,
        Field(description="Price per 1M output tokens. Null when pricing data is not available."),
    ]
    price_1m_cache_hit_tokens: Annotated[
        float | None,
        Field(
            description="Price per 1M cached input (cache hit / read) tokens. Null when the provider does not report cache pricing."
        ),
    ]
    price_1m_cache_write_tokens: Annotated[
        float | None,
        Field(description="Price per 1M cache write tokens. Null when the provider does not report cache pricing."),
    ]


class ImageArenaResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    slug: str
    model_creator: ArenaModelCreator
    elo: Annotated[float, Field(description="Arena Elo rating.")]
    ci_95: Annotated[float | None, Field(description="95% confidence interval. Null if unavailable.")]
    rank: Annotated[int | None, Field(description="Rank among current models by Elo.")]
    samples: Annotated[int, Field(description="Total number of arena samples.")]
    release_date: Annotated[str | None, Field(description="Release date.")]
    price_per_1k_images: Annotated[float | None, Field(description="Price per 1,000 images.")]
    open_weights_url: Annotated[
        str | None,
        Field(description="URL to open weights; can be used to infer if open weights."),
    ]
    categories: Annotated[
        list[ArenaCategory] | MISSING,
        Field(description="Per-category Elo breakdowns. Only present when include_categories=true."),
    ] = MISSING


class ImageArenaResultFree(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    slug: str
    model_creator: ArenaModelCreator
    elo: Annotated[float, Field(description="Arena Elo rating.")]
    ci_95: Annotated[float | None, Field(description="95% confidence interval. Null if unavailable.")]


class IntelligenceIndexCostPerTask(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    total_cost: Annotated[
        float,
        Field(
            description="Weighted average cost in USD per Intelligence Index task, across all Intelligence Index evaluations. Rounded to 4 decimal places."
        ),
    ]
    input_cost: Annotated[
        float | None,
        Field(description="Weighted average input cost in USD per Intelligence Index task. Null when not measured."),
    ]
    reasoning_cost: Annotated[
        float | None,
        Field(
            description="Weighted average reasoning-token cost in USD per Intelligence Index task. Null when not measured."
        ),
    ]
    answer_cost: Annotated[
        float | None,
        Field(
            description="Weighted average answer-token cost in USD per Intelligence Index task. Null when not measured."
        ),
    ]


class IntelligenceIndexTokenCounts(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    input_tokens: int
    answer_tokens: int
    output_tokens: int
    reasoning_tokens: int


class Licensing(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    is_open_weights: bool


class ModalitySet(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    text: bool
    image: bool
    video: bool
    speech: bool


class ModelCreator(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    country: Annotated[
        str | None | MISSING,
        Field(description="Pro tier only. Omitted on Free tier. ISO 3166-1 alpha-2 country code of the model creator."),
    ] = MISSING


class ModelPerformance(BaseModel):
    """
    Aggregated performance metrics across all providers serving this model. Individual fields are null when no measurements are available for that metric.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    percentile_05_output_tokens_per_second: float | None
    quartile_25_output_tokens_per_second: float | None
    median_output_tokens_per_second: float | None
    quartile_75_output_tokens_per_second: float | None
    percentile_95_output_tokens_per_second: float | None
    percentile_05_time_to_first_token_seconds: float | None
    quartile_25_time_to_first_token_seconds: float | None
    median_time_to_first_token_seconds: float | None
    quartile_75_time_to_first_token_seconds: float | None
    percentile_95_time_to_first_token_seconds: float | None
    median_time_to_first_answer_token_seconds: float | None
    median_end_to_end_response_time_seconds: float | None


class MusicArenaResultFree(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    model_creator: ArenaModelCreator
    elo: Annotated[float, Field(description="Arena Elo rating.")]
    ci_95: Annotated[float | None, Field(description="95% confidence interval. Null if unavailable.")]


class MusicGenre(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    label: Annotated[str, Field(description='Genre name (e.g. "Classical", "Electronic", "Pop").')]
    elo: float
    ci_95: float | None
    samples: int


class OmniscienceDomainBreakdown(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    accuracy: float
    omniscience: float
    hallucination_rate: float


class OpennessBreakdown(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    weights_access: float | None | MISSING = MISSING
    weights_license: float | None | MISSING = MISSING
    data_pretrain_access: float | None | MISSING = MISSING
    data_pretrain_license: float | None | MISSING = MISSING
    data_posttrain_access: float | None | MISSING = MISSING
    data_posttrain_license: float | None | MISSING = MISSING
    methodology_license: float | None | MISSING = MISSING
    methodology_disclosure: float | None | MISSING = MISSING
    artificial_analysis_openness_index: float | None | MISSING = MISSING


class PaginationMeta(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    page: Annotated[int, Field(description="Current page number (1-indexed).")]
    page_size: Annotated[int, Field(description="Number of items per page.")]
    total_pages: Annotated[int, Field(description="Total number of pages.")]
    has_more: Annotated[bool, Field(description="Whether there are more pages after the current one.")]


class Parameters(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    total: Annotated[float, Field(description="Total model parameters (in billions).")]
    active: Annotated[
        float | None,
        Field(description="Active parameters per forward pass (relevant for MoE models)."),
    ]


class Pricing(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    price_1m_blended_3_to_1: Annotated[
        float | None,
        Field(
            description="Blended price per 1M tokens (3:1 Input-Output ratio). Null when pricing data is not available."
        ),
    ]
    price_1m_blended_7_to_2_to_1: Annotated[
        float | None,
        Field(
            description="Blended price per 1M tokens (7:2:1 Cache-Input-Output ratio). Null when pricing data is not available."
        ),
    ]
    price_1m_input_tokens: Annotated[
        float | None,
        Field(description="Price per 1M input tokens. Null when pricing data is not available."),
    ]
    price_1m_output_tokens: Annotated[
        float | None,
        Field(description="Price per 1M output tokens. Null when pricing data is not available."),
    ]
    price_1m_cache_hit_tokens: Annotated[
        float | None,
        Field(
            description="Price per 1M cached input (cache hit / read) tokens. Null when the provider does not report cache pricing."
        ),
    ]
    price_1m_cache_write_tokens: Annotated[
        float | None,
        Field(description="Price per 1M cache write tokens. Null when the provider does not report cache pricing."),
    ]


class ProviderModelPerformance(BaseModel):
    """
    Performance metrics for a single (provider, model) pair. Individual fields are null when no measurements are available for that metric.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    percentile_05_output_tokens_per_second: float | None
    quartile_25_output_tokens_per_second: float | None
    median_output_tokens_per_second: float | None
    quartile_75_output_tokens_per_second: float | None
    percentile_95_output_tokens_per_second: float | None
    percentile_05_time_to_first_token_seconds: float | None
    quartile_25_time_to_first_token_seconds: float | None
    median_time_to_first_token_seconds: float | None
    quartile_75_time_to_first_token_seconds: float | None
    percentile_95_time_to_first_token_seconds: float | None
    median_time_to_first_answer_token_seconds: float | None
    median_end_to_end_response_time_seconds: float | None


class SpeechToSpeechProvider(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    slug: str
    price_per_hour_input: Annotated[float | None, Field(description="Price per hour of input audio.")]
    price_per_hour_output: Annotated[float | None, Field(description="Price per hour of output audio.")]
    time_to_first_audio_seconds: Annotated[float | None, Field(description="Time to first audio output in seconds.")]


class SpeechToSpeechResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    slug: str
    model_creator: ArenaModelCreator
    bba_score: Annotated[float | None, Field(description="Big Bench Audio score.")]
    fdb_score: Annotated[float | None, Field(description="Full Duplex Bench score.")]
    tau_voice_score: Annotated[
        float | None,
        Field(
            description="𝜏-Voice score (the model's best result across providers). Null when the model has no 𝜏-Voice measurements."
        ),
    ]
    providers: list[SpeechToSpeechProvider]


class SpeechToSpeechResultFree(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    slug: str
    model_creator: ArenaModelCreator
    bba_score: Annotated[float | None, Field(description="Big Bench Audio score.")]
    fdb_score: Annotated[float | None, Field(description="Full Duplex Bench score.")]
    tau_voice_score: Annotated[
        float | None,
        Field(
            description="𝜏-Voice score (the model's best result across providers). Null when the model has no 𝜏-Voice measurements."
        ),
    ]


class SpeechToTextModelResultFree(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    model_creator: ArenaModelCreator
    aa_wer_index: Annotated[float | None, Field(description="AA Word Error Rate index.")]


class SpeechToTextModelsFreeResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tier: Literal["free", "pro", "commercial"]
    data: list[SpeechToTextModelResultFree]


class SpeechToTextProvider(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    slug: str
    price_per_1k_minutes: float | None
    median_speed_factor: float | None
    aa_wer_index: float | None
    aa_agenttalk: float | None
    voxpopuli_cleaned_aa: float | None
    earnings_22_cleaned_aa: float | None


class TextToSpeechResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    slug: str
    model_creator: ArenaModelCreator
    elo: Annotated[float, Field(description="Arena Elo rating.")]
    ci_95: Annotated[float | None, Field(description="95% confidence interval. Null if unavailable.")]
    samples: Annotated[int, Field(description="Total number of arena samples.")]
    release_date: Annotated[str | None, Field(description="Release date.")]
    price_per_1m_characters: Annotated[float | None, Field(description="Price per 1 million characters.")]


class TextToSpeechResultFree(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    slug: str
    model_creator: ArenaModelCreator
    elo: Annotated[float, Field(description="Arena Elo rating.")]
    ci_95: Annotated[float | None, Field(description="95% confidence interval. Null if unavailable.")]


class VideoArenaResultFree(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    slug: str
    model_creator: ArenaModelCreator
    elo: Annotated[float, Field(description="Arena Elo rating.")]
    ci_95: Annotated[float | None, Field(description="95% confidence interval. Null if unavailable.")]


class VideoArenaResultPaid(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    slug: str
    model_creator: ArenaModelCreator
    elo: Annotated[float, Field(description="Arena Elo rating.")]
    ci_95: Annotated[float | None, Field(description="95% confidence interval. Null if unavailable.")]
    rank: Annotated[int | None, Field(description="Rank among current models by Elo.")]
    samples: Annotated[int, Field(description="Total number of arena samples.")]
    release_date: Annotated[str | None, Field(description="Release date.")]
    price_per_minute: Annotated[float | None, Field(description="Price per minute of video.")]
    open_weights_url: Annotated[
        str | None,
        Field(description="URL to open weights; can be used to infer if open weights."),
    ]
    categories: Annotated[
        list[ArenaCategory] | MISSING,
        Field(description="Per-category Elo breakdowns. Only present when include_categories=true."),
    ] = MISSING


class FreeIntelligenceIndexCost(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    total_cost: Annotated[
        float,
        Field(description="Total cost in USD to run the Intelligence Index evaluation."),
    ]
    cost_per_task: Annotated[
        FreeIntelligenceIndexCostPerTask | None,
        Field(
            description="Weighted average cost per Intelligence Index task, rounded to 4 decimal places. Null when token or pricing data is incomplete."
        ),
    ]


class FreeModelData(BaseModel):
    """
    Free-tier shape returned by `/api/v2/language/models/free`. Includes headline indices, median performance, and input/output pricing. Pro and Commercial keys also receive this shape when calling the `/free` endpoint.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    slug: str
    release_date: Annotated[str | None, Field(description='ISO date string (e.g. "2024-05-13").')]
    model_creator: FreeModelCreator | None
    evaluations: FreeEvaluations
    artificial_analysis_intelligence_index_cost: Annotated[
        FreeIntelligenceIndexCost | None,
        Field(
            description="Pre-calculated cost to run the Intelligence Index evaluation. Free tier exposes total cost plus `cost_per_task.total_cost`."
        ),
    ]
    pricing: Annotated[
        FreePricing,
        Field(description="Input and output token pricing. Pro tier adds blended pricing fields."),
    ]
    performance: Annotated[
        FreeModelPerformance,
        Field(
            description="Median performance metrics across all providers serving this model. Pro tier adds percentiles and quartiles."
        ),
    ]


class ImageArenaFreeResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tier: Literal["free", "pro", "commercial"]
    data: list[ImageArenaResultFree]


class ImageArenaResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tier: Literal["pro", "commercial"]
    data: list[ImageArenaResult]


class IntelligenceIndexCost(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    total_cost: Annotated[
        float,
        Field(description="Total cost in USD to run the Intelligence Index evaluation. Available on all tiers."),
    ]
    cost_per_task: Annotated[
        IntelligenceIndexCostPerTask | None,
        Field(
            description="Weighted average cost per Intelligence Index task, rounded to 4 decimal places. Null when token or pricing data is incomplete."
        ),
    ]
    input_cost: Annotated[
        float | None | MISSING,
        Field(description="Pro tier only. Omitted on Free tier. Null when not measured."),
    ] = MISSING
    reasoning_cost: Annotated[
        float | None | MISSING,
        Field(description="Pro tier only. Omitted on Free tier. Null when not measured."),
    ] = MISSING
    answer_cost: Annotated[
        float | None | MISSING,
        Field(description="Pro tier only. Omitted on Free tier. Null when not measured."),
    ] = MISSING


class LLMModelsFreeResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tier: Literal["free", "pro", "commercial"]
    intelligence_index_version: Annotated[
        float,
        Field(
            description="Version of the Artificial Analysis Intelligence Index the `artificial_analysis_intelligence_index` scores in this response belong to, as a number with the `v` dropped (e.g. `4.1` for v4.1). Being a number, it carries major.minor only — patch versions are not reflected here. See the Intelligence Index versioning section for what major, minor, and patch changes mean."
        ),
    ]
    pagination: PaginationMeta
    data: list[FreeModelData]


class Modalities(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    input: ModalitySet
    output: ModalitySet


class ModelProviderDataExternal(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    slug: str
    pricing: Pricing
    performance: ProviderModelPerformance
    context_window_tokens: Annotated[
        int | None,
        Field(description="Null when not set for the (provider, model) pair."),
    ]


class MusicArenaFreeResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tier: Literal["free", "pro", "commercial"]
    data: list[MusicArenaResultFree]


class MusicArenaResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    model_creator: ArenaModelCreator
    elo: Annotated[float, Field(description="Arena Elo rating.")]
    ci_95: Annotated[float | None, Field(description="95% confidence interval. Null if unavailable.")]
    samples: Annotated[int, Field(description="Total number of arena samples.")]
    genres: Annotated[
        list[MusicGenre] | MISSING,
        Field(description="Per-genre Elo breakdowns. Only present when include_genres=true."),
    ] = MISSING


class OmniscienceBreakdown(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    total: OmniscienceDomainBreakdown
    law: OmniscienceDomainBreakdown | None | MISSING = MISSING
    health: OmniscienceDomainBreakdown | None | MISSING = MISSING
    business: OmniscienceDomainBreakdown | None | MISSING = MISSING
    humanities_and_social_sciences: OmniscienceDomainBreakdown | None | MISSING = MISSING
    science_engineering_and_mathematics: OmniscienceDomainBreakdown | None | MISSING = MISSING
    software_engineering: OmniscienceDomainBreakdown | None | MISSING = MISSING


class SpeechToSpeechFreeResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tier: Literal["free", "pro", "commercial"]
    data: list[SpeechToSpeechResultFree]


class SpeechToSpeechResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tier: Literal["pro", "commercial"]
    data: list[SpeechToSpeechResult]


class SpeechToTextModelResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    model_creator: ArenaModelCreator
    aa_wer_index: Annotated[float | None, Field(description="AA Word Error Rate index.")]
    aa_agenttalk: Annotated[float | None, Field(description="AA AgentTalk WER.")]
    voxpopuli_cleaned_aa: Annotated[float | None, Field(description="VoxPopuli cleaned WER.")]
    earnings_22_cleaned_aa: Annotated[float | None, Field(description="Earnings22 cleaned WER.")]
    open_weights: Annotated[
        bool | None,
        Field(description="Whether the model has open weights. Null when unknown."),
    ]
    providers: Annotated[list[SpeechToTextProvider], Field(description="Per-provider data.")]


class SpeechToTextModelsResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tier: Literal["pro", "commercial"]
    data: list[SpeechToTextModelResult]


class TextToSpeechFreeResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tier: Literal["free", "pro", "commercial"]
    data: list[TextToSpeechResultFree]


class TextToSpeechResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tier: Literal["pro", "commercial"]
    data: list[TextToSpeechResult]


class VideoArenaFreeResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tier: Literal["free", "pro", "commercial"]
    data: list[VideoArenaResultFree]


class VideoArenaResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tier: Literal["pro", "commercial"]
    data: list[VideoArenaResultPaid]


class ModelDataExternal(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    name: str
    slug: str
    release_date: Annotated[str | None, Field(description='ISO date string (e.g. "2024-05-13").')]
    model_creator: ModelCreator | None
    reasoning_model: Annotated[bool | MISSING, Field(description="Pro tier only. Omitted on Free tier.")] = MISSING
    evaluations: Evaluations
    artificial_analysis_intelligence_index_cost: Annotated[
        IntelligenceIndexCost | None,
        Field(
            description="Pre-calculated cost to run the Intelligence Index evaluation. Free tier includes total_cost and cost_per_task.total_cost; Pro tier adds input_cost, reasoning_cost, answer_cost at both levels."
        ),
    ]
    artificial_analysis_intelligence_index_token_counts: Annotated[
        IntelligenceIndexTokenCounts | None | MISSING,
        Field(description="Pro tier only. Omitted on Free tier."),
    ] = MISSING
    pricing: Annotated[
        Pricing | MISSING,
        Field(
            description="Full pricing object including blended fields. Free tier returns input and output token prices only. See `FreePricing`."
        ),
    ] = MISSING
    performance: Annotated[
        ModelPerformance | MISSING,
        Field(
            description="Full performance object including quartiles and percentiles. Free tier returns medians only. See `FreeModelPerformance`."
        ),
    ] = MISSING
    context_window_tokens: Annotated[
        int | None | MISSING,
        Field(description="Pro tier only. Omitted on Free tier. Null when not set for the model."),
    ] = MISSING
    parameters: Annotated[
        Parameters | None | MISSING,
        Field(description="Pro tier only. Omitted on Free tier."),
    ] = MISSING
    modalities: Annotated[Modalities | MISSING, Field(description="Pro tier only. Omitted on Free tier.")] = MISSING
    licensing: Annotated[Licensing | MISSING, Field(description="Pro tier only. Omitted on Free tier.")] = MISSING
    huggingface_url: Annotated[
        str | None | MISSING,
        Field(
            description="Pro tier only. Omitted on Free tier. Canonical Hugging Face or model weights URL when available."
        ),
    ] = MISSING
    openrouter_api_id: Annotated[
        str | None | MISSING,
        Field(description="Pro tier only. Omitted on Free tier. OpenRouter API model identifier when available."),
    ] = MISSING
    evaluation_token_counts: Annotated[
        EvaluationTokenCounts | None | MISSING,
        Field(
            description="Pro tier only. Detail endpoint only (`/api/v2/language/models/{slug}`). Omitted on Free tier and list endpoint."
        ),
    ] = MISSING
    aa_omniscience_breakdown: Annotated[
        OmniscienceBreakdown | None | MISSING,
        Field(
            description="Pro tier only. Detail endpoint only (`/api/v2/language/models/{slug}`). Omitted on Free tier and list endpoint."
        ),
    ] = MISSING
    artificial_analysis_openness_index_breakdown: Annotated[
        OpennessBreakdown | MISSING,
        Field(
            description="Pro tier only. Detail endpoint only (`/api/v2/language/models/{slug}`). Omitted on Free tier and list endpoint."
        ),
    ] = MISSING
    providers: Annotated[
        list[ModelProviderDataExternal] | MISSING,
        Field(
            description="Commercial tier only. Detail endpoint only (`/api/v2/language/models/{slug}`). Omitted on Free and Pro tiers and on the list endpoint."
        ),
    ] = MISSING


class MusicArenaResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tier: Literal["pro", "commercial"]
    data: list[MusicArenaResult]


class LLMModelsResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tier: Literal["pro", "commercial"]
    intelligence_index_version: Annotated[
        float,
        Field(
            description="Version of the Artificial Analysis Intelligence Index the `artificial_analysis_intelligence_index` scores in this response belong to, as a number with the `v` dropped (e.g. `4.1` for v4.1). Being a number, it carries major.minor only — patch versions are not reflected here. See the Intelligence Index versioning section for what major, minor, and patch changes mean."
        ),
    ]
    pagination: PaginationMeta
    data: list[ModelDataExternal]
